- name: Login into OpenShift
  command: oc login --username={{ username }} --password={{ password }} --insecure-skip-tls-verify --server={{ master_url }}
  tags: openshift

- name: Creating Project 
  command: oc new-project {{ project_name }} --description="{{ project_description }}"
  tags: openshift
