---
- name: Delete all Repositories
  hosts: localhost
  connection: local
  tasks:
    - name: List all Repositories
      uri: method=GET body_format=json url={{ gogs_url_api }}/user/repos
           force_basic_auth=yes user={{ user | mandatory }} password={{ password | mandatory }}
      register: gogs_json_result
      tags: gogs

    - name: Delete all
      uri: method=DELETE body_format=json url={{ gogs_url_api }}/repos/{{ item.full_name }}
           force_basic_auth=yes user={{ user | mandatory }} password={{ password | mandatory }}
      register: gogs_delete_result
      with_items: "{{ gogs_json_result.json }}"
      failed_when: gogs_delete_result.status != 204
      tags: gogs
